# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-10 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictureall',
            name='isCarousel',
        ),
        migrations.RemoveField(
            model_name='pictureall',
            name='isGallery',
        ),
    ]
