# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-10 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180810_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureall',
            name='person',
            field=models.CharField(default='bishal', max_length=150),
        ),
    ]
